permissions:
  contents: read
  security-events: write

name: Gitleaks Secrets Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}
# (rest unchanged)

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect -v --redact --report-format sarif --report-path gitleaks.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: gitleaks.sarif }
