name: Gitleaks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    # Keep the workflow green even if secrets are detected (for demo)
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      # --exit-code 0 keeps the step successful while still writing a report
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect -v --redact --report-format sarif --report-path gitleaks.sarif --exit-code 0

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
