name: Semgrep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    # If Semgrep finds things, still finish green so the demo keeps flowing
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      # Run Semgrep with the CI ruleset and produce SARIF
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: "1"
          # do NOT set publishToken for public demo
          publishToken: ""

      # Upload SARIF so findings show under Security » Code scanning
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
